version: '3.9'
services:
  node:
    build: .
    environment:
      PORT: 3000
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: "user"
      DATABASE_PASSWORD: "123"
      DATABASE_NAME: "data"
    ports:
      - 3000:3000
    depends_on: 
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE="data"
      - MYSQL_USER="user"
      - MYSQL_PASSWORD="123"
      - MYSQL_ROOT_PASSWORD="123"
    